### ISSUE TITLE
`measure` does not recompute which items are in view

### ISSUE THREAD

**Issue by nick-keller** [TanStack/virtual#418]
### Describe the bug

Calling `measure` does not recomputes which items are in view, it keep the same items. I need to scroll to trigger an update and see the right items.

### Your minimal, reproducible example

https://codesandbox.io/s/condescending-lamport-bkqlmr?file=/src/main.tsx

### Steps to reproduce

1. Update the `estimateSize` function
2. Call `measure`

### Expected behavior

When calling `measure` after updating the `estimateSize` function I'd expect items to change size AND the range of visible items to be updated. 

Item size is updated as expected, but the items in view do not change (items that should now be visible are not, and items that should now be hidden are still rendered).

### How often does this bug happen?

Every time

### Screenshots or Videos

![CleanShot 2022-11-06 at 12 47 46](https://user-images.githubusercontent.com/2682443/200168771-4b06063a-cc8d-4a33-b9cb-137bd7401eac.gif)

### Platform

- OS: MacOS
- Browser: Chrome

### tanstack-virtual version

3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@nick-keller should be fixed in latest beta

**Comment by andylwelch** [comment]
I just ran into this issue too and updated to `beta.21` and after migrating to the new `rowVirtualizer.measureElement` pattern everything is working smoothly. So much nicer without all the manual triggers to resize. Thanks @piecyk

**Comment by nick-keller** [comment]
Hello @piecyk ,
I updated the codesandbox to `beta.21` but the same issue is still present apparently.

**Comment by piecyk** [comment]
@nick-keller basic you need to run `measure` in next tick, after state change, something like https://codesandbox.io/s/loving-phoebe-8wlp7s?file=/src/main.tsx

Maybe you can describe what is the idea here, as most case calling measure is not good idea 🤔

**Comment by nick-keller** [comment]
Alright got it, thx @piecyk!
I use the virtualizer for columns, and I compute columns widths based on container's width. Which means on first render I don't have the widths yet (I need to measure the container) and need to update the widths right after.

Also when the container is resized I need to re-compute the columns widths.

Is it a good use-case for calling `measure`?

**Comment by piecyk** [comment]
I would say that this is now supported out of box using ResizeObserver checkout dynamic example. If something is not working, create minimal example and I would be happy to help. Closing this issue as it's resolved. Thanks!
