### ISSUE TITLE
3.0.0-beta.21 - ResizeObserver is not defined in SSR

### ISSUE THREAD

**Issue by raskyer** [TanStack/virtual#419]
### Describe the bug

I try to use tanstack virtual with Remix and I have the following issue when the page (where the tanstack virtual is render) : 

`ReferenceError: ResizeObserver is not defined
    at new Virtualizer (node_modules\@tanstack\virtual-core\build\esm\index.js:211:19)
    at node_modules\@tanstack\react-virtual\src\index.tsx:34:11
    at useReducer (node_modules\react-dom\cjs\react-dom-server.node.development.js:1537:57)
    at Object.useState (node_modules\react-dom\cjs\react-dom-server.node.development.js:1475:10)
    at Object.useState (node_modules\react\cjs\react.development.js:1508:21)
    at useVirtualizerBase (node_modules\@tanstack\react-virtual\src\index.tsx:33:28)
    at useWindowVirtualizer (node_modules\@tanstack\react-virtual\src\index.tsx:73:10)
    at VirtualizedActionList (app\components\lists\VirtualizedList.tsx:33:23)
    at processChild (node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at handleRequest (app\entry.server.tsx:54:16)
    at handleDocumentRequest (node_modules\@remix-run\server-runtime\dist\server.js:417:12)
    at requestHandler (node_modules\@remix-run\server-runtime\dist\server.js:72:18)`

### Your minimal, reproducible example

none applicable

### Steps to reproduce

- Have a remix project
- Install tanstack 
- Make a page with useWindowVirtualizer
- Arrive on this page with SSR (not CSR)

### Expected behavior

Working without issue

### How often does this bug happen?

Every time

### Platform

- OS : ALL
- Browser : ALL

### tanstack-virtual version

v3.0.0-beta.21

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by raskyer** [comment]
I think this PR : https://github.com/TanStack/virtual/pull/405/files is responsible

**Comment by raskyer** [comment]
We should probably delay the ResizeObserver instanciation inside a useEffect in order to avoid panic at server side level

**Comment by piecyk** [comment]
Thanks for reporting, #420 should fix this issue.

**Comment by lakmalniranga** [comment]
@piecyk I still get the issue with the testing. But I don't see any issues on a development server. 

**Screenshots**
![Screenshot from 2022-11-09 23-55-07](https://user-images.githubusercontent.com/17959894/200959754-dca93524-d8c7-41d9-ad30-4db68b0f740d.png)

**Steps to reproduce:** 
1. Create a react project using Vite
2. Add a test case to render a row virtualizer.

**Platform**
- OS: Ubuntu
- Browser: ALL

**How often does this bug happen?**
- Every time

**tanstack-virtual version**
- 3.0.0-beta.22

**Additional context**
I was able to get around the issue by mocking `ResizeObserver` and `IntersectionObserver` globally on the test setup. I'm pretty new to the frontend space (I worked as a backend developer). If my workaround is actually something that we have to do during the testing, my apologies!

![Screenshot from 2022-11-09 23-55-51](https://user-images.githubusercontent.com/17959894/200959842-c84641a1-eb41-43ab-b462-fd9b40889764.png)

**Comment by piecyk** [comment]
Hi @lakmalniranga yes in test you need to provide ResizeObserver, in context of SSR we can delay to create the instance till the first measurement.

Best is to use `resize-observer-polyfill` package, then in test setup just attach it to global

```tsx
import ResizeObserver from 'resize-observer-polyfill'

global.ResizeObserver = ResizeObserver
```

**Comment by lakmalniranga** [comment]
@piecyk Thank you so much for the clarification!

**Comment by jangxyz** [comment]
I have a similar case, which is not for testing. I am running on svelte-kit, with `v3.0.0-beta.23`
The server reports error on the same line as @lakmalniranga noted, on [virtual-core/index.js:95](https://github.com/TanStack/virtual/blob/v3.0.0-beta.23/packages/virtual-core/src/index.ts#L80):

```typescript
export const observeElementRect = (
  instance: Virtualizer<any, any>,
  cb: (rect: Rect) => void,
) => {
  const observer = new ResizeObserver((entries) => { // ← HERE
    cb({
      width: entries[0]?.contentRect.width as number,
      height: entries[0]?.contentRect.height as number,
    })
  })
  if (!instance.scrollElement) {
    return
  }
  cb(instance.scrollElement.getBoundingClientRect())
  observer.observe(instance.scrollElement)
  return () => { observer.unobserve(instance.scrollElement) }
}
```

Skimming through PR #420 looks like it fixes the case on `_didMount`, but this error appears during `_willUpdate`.

<details>
<summary>screenshot showing call in `_willUpdate`</summary>

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/52015/202052919-fe6d641c-33fa-4f20-bd8d-9b4cc629341f.png">

</details>

I have tried some workarounds, and think the api has some room for improvement.

* I tried adding `initialRect` option as said in the [docs](https://react-virtual-v2.tanstack.com/docs/api), but did not work.
* I found out that passing `observeElementRect` option would override the behavior, and tried the following;
  * (A) Move the code `if (!instance.scrollElement)` part above the `new ResizeObserver` part, it would return on SSR. 
  * (B) Check for `globalThis.ResizeObserver` , like mentioned in the [comment](https://github.com/TanStack/virtual/issues/419#issuecomment-1307094033).
  * (C) Check using `import { browser } from "$app/environment";`, a more svelte-kit way.
  * (D) Attach the `resize-observer-polyfill`, though the idea of adding a polyfill in SSR just to ignore the issue seems not right.

```javascript
observeElementRect: (instance, cb) => {
  //if (!instance.scrollElement) { return; }                              // (A)
  //if (globalThis.ResizeObserver === undefined) { return; }              // (B)
  //if (!browser) { return; }                                             // (C)
  //if (!browser) { globalThis.ResizeObserver = ResizeObserverPolyfill; } // (D)

  const observer = new ResizeObserver((entries) => {
    var _entries$, _entries$2;
    cb({
      width: (_entries$ = entries[0]) == null ? void 0 : _entries$.contentRect.width,
      height: (_entries$2 = entries[0]) == null ? void 0 : _entries$2.contentRect.height,
    });
  });
  if (!instance.scrollElement) {
    return;
  }
  cb(instance.scrollElement.getBoundingClientRect());
  observer.observe(instance.scrollElement);
  return () => { observer.unobserve(instance.scrollElement); };
},
```

Which one would be ideal? 

Any of the above does work, but the idea of "copying the whole implementation just to add a few if statements upfront" seems overkill. Maybe the first alternative -- moving the `instance.scrollElement` check beforehand would be a clear solution?

**Comment by JohnRSim** [comment]
@jangxyz did you make sure to initial virtualiser onMount so it doesn't execute server side.. 
This was the fix I used.

```
onMount(async () => {
	virtualizer = createVirtualizer(options);
})
```

**Comment by jpolivra** [comment]
> Hi @lakmalniranga yes in test you need to provide ResizeObserver, in context of SSR we can delay to create the instance till the first measurement.
> 
> Best is to use `resize-observer-polyfill` package, then in test setup just attach it to global
> 
> ```tsx
> import ResizeObserver from 'resize-observer-polyfill'
> 
> global.ResizeObserver = ResizeObserver
> ```

Had the same issue when running my test using Vitest. Fixed by applying @piecyk solution to the tests setup file.
